site_name: "ConfIDent metadata schema"
theme:
  name: material
  analytics:
    gtag: G-2SYBSJVZ23
#  palette:
#    scheme: slate
#    primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      #anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      #alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
#  - Home: home.md
  - Index: index.md
  - Academic Event: Event.md
  - Academic Event Series: EventSeries.md
  - About: about.md
site_url: https://tibhannover.github.io/ConfIDent_schema/
repo_url: https://github.com/TIBHannover/ConfIDent_schema
